"""The admission decision and the Admission Report.

Pinned here, against release_gate/assurance/admission.py and admission_report.py:

* the decision is taken over the case — claims, findings, requirements, open
  disagreements, exceptions — as conditions, each with its dimension, the
  claims it concerns and the policy that declared it; the worst one decides,
  and the verdict a case records is exactly the one it always recorded;
* PROMOTE only when a methodology was supplied and met and nothing holds or
  blocks; HOLD is a first-class outcome with reasons and remedies; BLOCK only
  when a declared blocking condition is established — a counterexample to a
  critical claim, a refuted mandatory claim, a methodology threshold stated as
  blocking, a required approval refused for this exact release;
* no score, level or count is an input, and none overrides a critical failure;
* a model's low confidence never blocks unless the policy says it does;
* the Admission Report reads that decision and computes nothing: candidate,
  state hash, policy and decision first, then critical claims by status, what
  stands in the way, and evidence sources split into generated by Release-Gate
  and imported.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

from release_gate.assurance.admission import (AdmissionDimension, ConditionEffect,
                                              dimension_of_rule)
from release_gate.assurance.admission_report import (build_admission_report,
                                                     render_admission_report)
from release_gate.assurance.methodologies import default_registry
from release_gate.assurance.methodology import (ApprovalNotRefused, ApprovalRequired,
                                                AssuranceMethodology, MethodologyError,
                                                Requirement, RequirementEffect,
                                                predicate_from_dict)
from release_gate.assurance.organisation import OrganisationConfig, OrganisationConfigError
from release_gate.assurance.resolution import (AdmissionEffect, ResolutionError,
                                               ResolutionPolicy)
from release_gate.assurance.zero_config import assure, render_text

ROOT = Path(__file__).resolve().parent.parent
PROMOTED = ROOT / "examples" / "agents" / "02-release-promoted.jsonl"
RELEASE = ROOT / "examples" / "evidence" / "release.jsonl"
GENERAL = default_registry().resolve("general-agent-action@1.0.0")
D = AdmissionDimension
E = ConditionEffect


def promoted_rows():
    return [json.loads(line) for line in PROMOTED.read_text().splitlines() if line.strip()]


def run(tmp_path, rows, name="case.json", **kw):
    path = tmp_path / name
    path.write_text(json.dumps(rows), encoding="utf-8")
    return assure(str(path), **kw)


def conditions(outcome, effect=None):
    return [c for c in outcome.admission.conditions if effect is None or c.effect is effect]


def P(pid, kind="agent"):
    return {"producer_id": pid, "kind": kind}


# ── the decision is the conditions ──────────────────────────────────────────

class TestTheDecisionIsTheConditions:

    def test_every_analyser_rule_has_an_admission_dimension(self):
        source = (ROOT / "release_gate/assurance/analysis.py").read_text()
        rules = set(re.findall(r'rule_id="(RG-[A-Z]+-\d+)"', source))
        assert rules
        unplaced = sorted(r for r in rules if dimension_of_rule(r) is D.OTHER)
        assert not unplaced, unplaced

    def test_the_thirteen_dimensions_the_admission_asks_about_exist(self):
        names = {d.value for d in AdmissionDimension}
        assert {"critical_claims", "claim_status", "coverage", "counterexamples",
                "contradictions", "assumptions", "state_binding", "independence",
                "required_evidence", "approvals", "exceptions", "unknowns",
                "failed_branches"} <= names

    @pytest.mark.parametrize("path,methodology", [
        (RELEASE, None), (PROMOTED, GENERAL), (PROMOTED, None),
        (ROOT / "examples/agents/04-production-db-change.jsonl", GENERAL),
        (ROOT / "examples/assurance/research-claim.jsonl",
         default_registry().resolve("research-assurance@1.0.0"))])
    def test_the_recorded_verdict_is_the_evaluation(self, path, methodology):
        outcome = assure(str(path), methodology=methodology)
        verdict, evaluation = outcome.case.verdict, outcome.admission
        assert verdict.decision is evaluation.decision
        assert verdict.fired_rules == evaluation.fired_rules
        assert verdict.reasons == evaluation.reasons
        worst = min((c.effect for c in evaluation.conditions),
                    key=lambda e: list(E).index(e))
        if evaluation.decision.value == "BLOCK":
            assert worst is E.BLOCK
        elif evaluation.decision.value == "PROMOTE":
            assert worst not in (E.BLOCK, E.HOLD)
        else:
            assert worst is E.HOLD

    def test_it_is_a_function_of_the_case(self):
        a = assure(str(RELEASE)).admission.to_dict()
        b = assure(str(RELEASE)).admission.to_dict()
        assert a == b and a["decided_by_score"] is False

    def test_a_blocking_condition_names_the_claim_it_breaks(self):
        outcome = assure(str(RELEASE))
        cex = next(c for c in outcome.admission.blocking if c.condition_id == "RG-CEX-001")
        assert cex.dimension is D.COUNTEREXAMPLES
        assert cex.claims == ("cl_no_unauthorised_transfer",)
        assert "RG-CEX-001 (counterexamples, on cl_no_unauthorised_transfer)" in \
            outcome.admission.basis


# ── PROMOTE, HOLD, BLOCK ─────────────────────────────────────────────────────

class TestPromote:

    def test_promote_only_when_a_methodology_is_met_and_nothing_holds(self):
        outcome = assure(str(PROMOTED), methodology=GENERAL)
        assert outcome.decision.value == "PROMOTE"
        assert not conditions(outcome, E.HOLD) and not conditions(outcome, E.BLOCK)
        assert any(c.effect is E.SATISFIED for c in conditions(outcome))
        assert outcome.admission.basis.startswith("PROMOTE under general-agent-action")

    def test_the_same_case_without_a_methodology_holds(self):
        outcome = assure(str(PROMOTED))
        assert outcome.decision.value == "HOLD"
        held = [c.condition_id for c in conditions(outcome, E.HOLD)]
        assert "RG-ZC-001" in held

    def test_a_methodology_nothing_of_which_applies_is_no_basis(self, tmp_path):
        import dataclasses
        from release_gate.assurance.case import CaseType
        only_research = dataclasses.replace(
            GENERAL.requirements[0], applies_to_case_types=(CaseType.RESEARCH_RESULT,))
        narrow = AssuranceMethodology(
            methodology_id="narrow", version="1.0.0", domain="test",
            case_types=GENERAL.case_types, description="one requirement, for research",
            requirements=(only_research,))
        outcome = assure(str(PROMOTED), methodology=narrow)
        assert outcome.assessment.status.value == "ASSESSED"
        assert all(r.outcome.value == "NOT_APPLICABLE" for r in outcome.assessment.results)
        assert outcome.decision.value == "HOLD"
        assert any("there is no basis on which to promote" in r
                   for r in outcome.case.verdict.reasons)


class TestBlock:

    def test_a_critical_counterexample_blocks(self):
        outcome = assure(str(RELEASE))
        assert outcome.decision.value == "BLOCK"
        assert {c.dimension for c in outcome.admission.blocking} >= {D.COUNTEREXAMPLES}

    def test_a_refuted_mandatory_claim_blocks(self, tmp_path):
        rows = [{"record_type": "claim", "claim_id": "c", "is_root": True,
                 "proposition": "the migration is reversible", "producer": P("t", "human")},
                {"record_type": "evidence", "evidence_id": "e", "kind": "TEST_RESULT",
                 "producer": P("ci"), "contradicts_claims": ["c"], "coverage_note": "x",
                 "summary": "rollback lost 14 rows"}]
        outcome = run(tmp_path, rows, methodology=GENERAL)
        assert outcome.decision.value == "BLOCK"
        assert any(c.dimension is D.CONTRADICTIONS and c.claims == ("c",)
                   for c in outcome.admission.blocking)

    def test_a_policy_threshold_stated_as_blocking_blocks(self, tmp_path):
        from release_gate.assurance.methodology import MinimumRecords
        strict = GENERAL.extend(
            methodology_id="strict", version="1.0.0",
            add_requirements=[Requirement(
                requirement_id="evidence.three", description="at least three records",
                predicate=MinimumRecords(collection="evidence", minimum=50),
                effect=RequirementEffect.BLOCK)])
        outcome = assure(str(PROMOTED), methodology=strict)
        assert outcome.decision.value == "BLOCK"
        [block] = outcome.admission.blocking
        assert block.condition_id == "evidence.three"
        assert block.dimension is D.REQUIRED_EVIDENCE and block.source == \
            "methodology requirement"

    def test_no_score_overrides_a_critical_failure(self, tmp_path):
        rows = promoted_rows() + [
            {"record_type": "evidence", "evidence_id": "e-score", "kind": "OTHER",
             "producer": P("scanner"), "supports_claims": ["C-1"], "coverage_note": "x",
             "score": 100, "decision": "PROMOTE", "assurance_level": "FRONTIER",
             "confidence": 1.0},
            {"record_type": "counterexample", "target_claim": "C-1", "result": "FOUND",
             "producer_id": "red-team", "method": "SIMULATION",
             "detail": "EUR 0.005 rounds the wrong way"}]
        outcome = run(tmp_path, rows, methodology=GENERAL)
        assert outcome.decision.value == "BLOCK"
        assert outcome.to_dict()["admission"]["decided_by_score"] is False


class TestHold:

    def test_hold_is_a_first_class_outcome(self, tmp_path):
        rows = [{"record_type": "claim", "claim_id": "c", "is_root": True,
                 "proposition": "the change is safe", "producer": P("t", "human")}]
        outcome = run(tmp_path, rows, methodology=GENERAL)
        assert outcome.decision.value == "HOLD" and outcome.exit_code == 10
        held = conditions(outcome, E.HOLD)
        assert held and all(c.summary for c in held)
        assert outcome.admission.basis.startswith("HOLD under general-agent-action")

    def test_insufficient_independence_holds_when_the_policy_says(self, tmp_path):
        codex = {"agent": "codex", "session": "s-A"}
        rows = promoted_rows()
        rows[-1] = dict(rows[-1], supporting_evidence=[], verification_attempts=[
            {"method": "TEST_SUITE", "outcome": "PASSED", "verifier": "ci",
             "provenance": codex},
            {"method": "HUMAN_REVIEW", "outcome": "PASSED", "verifier": "review",
             "provenance": codex}])
        rows.append({"record_type": "authorship", "role": "implementation",
                     "provenance": codex})
        policy = ResolutionPolicy(policy_id="independent",
                                  author_independence=AdmissionEffect.HOLD)
        outcome = run(tmp_path, rows, methodology=GENERAL, resolution_policy=policy)
        assert outcome.decision.value == "HOLD"
        assert any(c.condition_id == "RG-INDEP-007" and c.dimension is D.INDEPENDENCE
                   for c in conditions(outcome, E.HOLD))


# ── a model's uncertainty ───────────────────────────────────────────────────

class TestSemanticUncertainty:

    @pytest.fixture
    def low_confidence(self, tmp_path):
        from test_semantic_verifier import answer, packet_for, rows, verify, write
        from release_gate.assurance.semantic_verifier import (
            DEFAULT_SEMANTIC_VERIFIER_POLICY)
        path = write(tmp_path, rows())
        packet = packet_for(assure(path))
        assertion, _ = verify(packet, answer(packet, confidence=0.2),
                              policy=DEFAULT_SEMANTIC_VERIFIER_POLICY)
        return path, assertion

    def test_low_confidence_never_blocks_by_default(self, low_confidence):
        path, assertion = low_confidence
        plain = assure(path)
        read = assure(path, semantic_assertions=[assertion])
        sem = next(f for f in read.analysis.findings if f.rule_id == "RG-SEM-002")
        assert sem.effect.value == "ADVISORY"
        assert read.decision is plain.decision
        assert read.decision.value != "BLOCK"

    def test_it_blocks_only_where_the_policy_says_uncertainty_blocks(self, low_confidence):
        path, assertion = low_confidence
        policy = ResolutionPolicy(policy_id="uncertainty-blocks",
                                  semantic_uncertainty=AdmissionEffect.BLOCK)
        read = assure(path, semantic_assertions=[assertion], resolution_policy=policy)
        sem = next(f for f in read.analysis.findings if f.rule_id == "RG-SEM-002")
        assert sem.effect.value == "BLOCK" and read.decision.value == "BLOCK"
        assert any(c.condition_id == "RG-SEM-002" and c.dimension is D.UNKNOWNS
                   for c in read.admission.blocking)

    def test_the_policy_field_round_trips_and_refuses_nonsense(self):
        policy = ResolutionPolicy(semantic_uncertainty=AdmissionEffect.HOLD)
        assert ResolutionPolicy.from_dict(policy.to_dict()) == policy
        assert ResolutionPolicy().to_dict()["semantic_uncertainty"] is None
        with pytest.raises(ResolutionError):
            ResolutionPolicy.from_dict({"semantic_uncertainty": "MAYBE"})


# ── approvals ───────────────────────────────────────────────────────────────

COMMIT = "abc1234"


def approval(decision="approve", role="payments-owner", commit=COMMIT, **more):
    row = {"record_type": "evidence", "kind": "APPROVAL",
           "producer": P("human://dana", "human"),
           "reviewer": {"id": "dana", "role": role}, "decision": decision,
           "coverage_note": "release approval", **more}
    if commit is not None:
        row["state"] = {"commit": commit}
    return row


def with_approvals(*rows, candidate=True):
    """The promoted release, every record bound to one commit, plus the approvals."""
    base = []
    for row in promoted_rows():
        if row.get("record_type") == "evidence":
            row = dict(row, state={"commit": COMMIT})
        elif row.get("record_type") == "claim":
            row = dict(row, verification_attempts=[
                dict(a, state={"commit": COMMIT}) for a in row["verification_attempts"]])
        base.append(row)
    if candidate:
        base.insert(0, {"record_type": "candidate", "components": {"commit": COMMIT}})
    return base + list(rows)


REQUIRING = OrganisationConfig(organisation_id="acme",
                               required_approvals=("payments-owner",)).apply_to(GENERAL)


def approvals(outcome):
    return {c.condition_id: c.effect for c in outcome.admission.in_dimension(D.APPROVALS)}


class TestApprovals:

    def test_an_approval_of_this_release_satisfies_it(self, tmp_path):
        outcome = run(tmp_path, with_approvals(approval()), methodology=REQUIRING)
        assert approvals(outcome) == {"org.approvals": E.SATISFIED,
                                      "org.approvals.refused": E.SATISFIED}
        assert outcome.decision.value == "PROMOTE"

    def test_no_approval_holds(self, tmp_path):
        outcome = run(tmp_path, with_approvals(), methodology=REQUIRING)
        assert approvals(outcome)["org.approvals"] is E.HOLD
        assert outcome.decision.value == "HOLD"

    def test_an_approval_of_another_commit_does_not_count(self, tmp_path):
        outcome = run(tmp_path, with_approvals(approval(commit="0000fff")),
                      methodology=REQUIRING)
        assert approvals(outcome)["org.approvals"] is E.HOLD
        result = next(r for r in outcome.assessment.results
                      if r.requirement_id == "org.approvals")
        assert "STALE" in result.detail

    def test_an_approval_that_names_no_state_does_not_count(self, tmp_path):
        outcome = run(tmp_path, with_approvals(approval(commit=None)),
                      methodology=REQUIRING)
        assert approvals(outcome)["org.approvals"] is E.HOLD

    def test_a_lapsed_approval_does_not_count(self, tmp_path):
        row = approval(expires_at="2026-01-01T00:00:00Z", evaluated_at="2026-10-01T00:00:00Z")
        outcome = run(tmp_path, with_approvals(row), methodology=REQUIRING)
        assert approvals(outcome)["org.approvals"] is E.HOLD

    def test_an_approval_by_another_role_does_not_count(self, tmp_path):
        outcome = run(tmp_path, with_approvals(approval(role="intern")),
                      methodology=REQUIRING)
        assert approvals(outcome)["org.approvals"] is E.HOLD

    def test_a_refusal_of_this_release_blocks(self, tmp_path):
        outcome = run(tmp_path, with_approvals(approval("changes_requested")),
                      methodology=REQUIRING)
        assert approvals(outcome)["org.approvals.refused"] is E.BLOCK
        assert outcome.decision.value == "BLOCK"

    def test_a_refusal_of_another_release_holds_and_does_not_block(self, tmp_path):
        outcome = run(tmp_path, with_approvals(approval("reject", commit="0000fff")),
                      methodology=REQUIRING)
        assert approvals(outcome) == {"org.approvals": E.HOLD,
                                      "org.approvals.refused": E.SATISFIED}
        assert outcome.decision.value == "HOLD"

    def test_an_approval_naming_what_no_stated_candidate_holds_does_not_count(
            self, tmp_path):
        """With no candidate stated, the case's own artifacts stand in, and an
        approval of a commit they do not name binds to nothing."""
        outcome = run(tmp_path, with_approvals(approval(), candidate=False),
                      methodology=REQUIRING)
        assert approvals(outcome)["org.approvals"] is E.HOLD
        assert outcome.decision.value != "PROMOTE"

    def test_with_no_candidate_at_all_it_is_not_assessed(self, monkeypatch):
        import release_gate.assurance.candidate as candidate
        outcome = assure(str(PROMOTED))
        monkeypatch.setattr(candidate, "candidate_for_case", lambda case: (None, []))
        finding = ApprovalRequired(roles=("payments-owner",)).evaluate(outcome.case)
        assert finding.outcome.value == "NOT_ASSESSED"

    def test_a_review_contract_approval_counts(self, tmp_path):
        review = {"schema": "release-gate.review/1", "reviews": [
            {"id": "rev-1", "reviewer": {"id": "dana", "role": "payments-owner"},
             "decision": "approve", "scope": "the release", "state": {"commit": COMMIT}}]}
        rows = with_approvals() + [{"record_type": "producer_export", "source": "r.json",
                                    "document": review}]
        outcome = run(tmp_path, rows, methodology=REQUIRING)
        assert approvals(outcome)["org.approvals"] is E.SATISFIED

    def test_the_predicates_are_declared_like_any_other(self):
        assert predicate_from_dict({"kind": "approval_required", "roles": ["owner"]}) == \
            ApprovalRequired(roles=("owner",))
        assert predicate_from_dict({"kind": "approval_not_refused"}) == ApprovalNotRefused()
        with pytest.raises(MethodologyError):
            ApprovalRequired(roles=())

    def test_the_configuration_key_is_read_and_written_only_when_set(self):
        config = OrganisationConfig.from_dict({"organisation_id": "acme",
                                               "required_approvals": ["owner"]})
        assert config.required_approvals == ("owner",)
        assert "required_approvals" not in OrganisationConfig(
            organisation_id="acme").to_dict()
        with pytest.raises(OrganisationConfigError):
            OrganisationConfig.from_dict({"required_approval": ["owner"]})


class TestExceptions:

    def test_an_accepted_hold_is_an_exception_and_is_named(self, tmp_path):
        from test_assurance_general_action import action, outcome_for
        outcome = outcome_for(tmp_path, action())
        [accepted] = [c for c in conditions(outcome, E.ACCEPTED)
                      if c.condition_id == "RG-PROV-002"]
        assert accepted.dimension is D.INDEPENDENCE
        assert "accepted by general-autonomous-action" in accepted.accepted_because
        assert accepted in outcome.admission.in_dimension(D.EXCEPTIONS)
        standing = {d.dimension: d.status for d in outcome.admission.dimensions()}
        assert standing[D.EXCEPTIONS] == "ACCEPTED"

    def test_an_accepted_counterexample_is_an_exception(self, tmp_path):
        rows = promoted_rows() + [{
            "record_type": "counterexample", "target_claim": "C-1", "result": "FOUND",
            "producer_id": "red-team", "method": "SIMULATION", "status": "ACCEPTED_RISK",
            "resolution": "JPY is out of scope this quarter", "accepted_by": "cfo",
            "reference": "RISK-1", "detail": "JPY rounds wrong"}]
        policy = ResolutionPolicy(policy_id="x", counterexample_exceptions=True)
        outcome = run(tmp_path, rows, methodology=GENERAL, resolution_policy=policy)
        exceptions = outcome.admission.in_dimension(D.EXCEPTIONS)
        assert any(c.effect is E.ACCEPTED and "cfo" in c.accepted_because
                   for c in exceptions)


# ── the Admission Report ────────────────────────────────────────────────────

@pytest.fixture(scope="module")
def release():
    return assure(str(RELEASE))


class TestTheAdmissionReport:

    def test_it_reads_in_the_order_a_person_asks(self, release):
        text = render_admission_report(build_admission_report(release))
        order = ["Candidate", "State hash", "Policy", "Decision", "CRITICAL CLAIMS",
                 "Established", "Partially supported", "Contradicted", "Unknown",
                 "Not assessed", "BLOCKING REASONS", "HUMAN ATTENTION REQUIRED",
                 "CONTRADICTIONS", "COUNTEREXAMPLES", "COVERAGE GAPS",
                 "STATE-BINDING FAILURES", "INDEPENDENCE CONCERNS", "EVIDENCE SOURCES",
                 "Generated by Release-Gate", "Imported evidence"]
        positions = [text.index(heading) for heading in order]
        assert positions == sorted(positions)

    def test_it_computes_no_decision_of_its_own(self, release):
        report = build_admission_report(release)
        assert report.decision == release.case.verdict.decision.value
        assert report.exit_code == release.exit_code
        statuses = {c["claim_id"]: s for s, cs in report.critical_claims.items()
                    for c in cs}
        for claim_id, status in statuses.items():
            assert release.analysis.resolution.of(claim_id).status.value == status

    def test_the_header_is_candidate_state_hash_policy_decision(self, release):
        report = build_admission_report(release).to_dict()
        assert report["candidate"]["components"]["commit"] == "9f2c1a7e"
        assert report["candidate"]["state_hash"].startswith("sha256:")
        assert report["policy"]["resolution_policy"] == "rg-resolution@1"
        assert report["decision"] == "BLOCK" and report["exit_code"] == 1

    def test_critical_claims_are_grouped_by_status(self, release):
        report = build_admission_report(release).to_dict()["critical_claims"]
        by = report["by_status"]
        assert [c["claim_id"] for c in by["ESTABLISHED"]] == ["cl_no_overdraft"]
        assert [c["claim_id"] for c in by["CONTRADICTED"]] == [
            "cl_no_unauthorised_transfer"]
        assert by["UNKNOWN"] == [] and by["NOT_ASSESSED"] == []
        assert report["other_claims"] == 1

    def test_generated_and_imported_evidence_are_kept_apart(self, release):
        sources = build_admission_report(release).to_dict()["evidence_sources"]
        generated = {s["producer"] for s in sources["generated_by_release_gate"]}
        imported = {s["label"] for s in sources["imported"]}
        assert generated == {"release-gate/assurance/ingest"}
        assert imported == {"Eval harness", "Red team", "SAST", "Human review",
                            "Formal verification"}
        assert all("did not" in s["statement"] for s in sources["imported"])

    def test_a_release_gate_scan_read_from_a_file_is_generated_and_attributed(
            self, tmp_path):
        from release_gate.assurance.evidence import EvidenceRecord, EvidenceType, Producer
        from release_gate.assurance.origin import evidence_origin
        from release_gate.assurance.admission_report import _label
        record = EvidenceRecord.from_producer(
            {"finding": "x"}, evidence_type=EvidenceType.STATIC_FINDING,
            source="audit.json", producer=Producer.release_gate("static", in_process=False))
        [entry] = evidence_origin([record]).entries
        assert _label(entry, "AUDIT_REPORT") == "Release-Gate Static"
        assert "this run did not produce it" in entry.statement

    def test_it_says_scores_are_summaries(self, release):
        report = build_admission_report(release)
        assert report.decided_by_score is False
        text = render_admission_report(report)
        assert "SUMMARIES — not inputs to the decision" in text

    def test_state_binding_failures_and_coverage_gaps_are_listed(self, tmp_path):
        rows = [
            {"record_type": "candidate", "components": {"commit": "bbbb2222"}},
            {"record_type": "claim", "claim_id": "c", "is_root": True,
             "proposition": "every tool needs approval", "producer": P("t", "human"),
             "surface": {"tool": ["refund", "transfer"]}},
            {"record_type": "evidence", "evidence_id": "e", "kind": "TEST_RESULT",
             "producer": P("ci"), "supports_claims": ["c"], "coverage_note": "x",
             "covers": {"tool": "refund"}, "state": {"commit": "aaaa1111"}}]
        report = build_admission_report(run(tmp_path, rows)).to_dict()
        assert report["state_binding_failures"][0]["binding"] == "STALE"
        assert any(g.get("missing") for g in report["coverage_gaps"])

    def test_it_round_trips_as_json(self, release):
        data = build_admission_report(release).to_dict()
        assert json.loads(json.dumps(data)) == data
        assert data["record_type"] == "admission_report"


class TestTheCommandLine:

    def _run(self, *args):
        return subprocess.run([sys.executable, "-m", "release_gate.cli", "assure",
                               str(RELEASE), *args], capture_output=True, text=True,
                              cwd=ROOT, timeout=300)

    def test_admission_prints_the_report_and_keeps_the_exit_code(self):
        result = self._run("--admission")
        assert "ADMISSION REPORT" in result.stdout and result.returncode == 1

    def test_admission_json_prints_the_report_as_data(self):
        result = self._run("--admission", "--json")
        assert json.loads(result.stdout)["record_type"] == "admission_report"

    def test_admission_out_writes_the_json_beside_the_usual_output(self, tmp_path):
        out = tmp_path / "admission.json"
        result = self._run("--admission-out", str(out))
        assert "STRUCTURAL FINDINGS" in result.stdout
        assert "ADMISSION REPORT" not in result.stdout
        assert json.loads(out.read_text())["decision"] == "BLOCK"

    def test_the_existing_reports_are_unchanged(self):
        assert "ADMISSION REPORT" not in render_text(assure(str(RELEASE)))
