"""
Evidence Pack generator for release-gate.

Produces an audit-ready set of artefacts:
  - readiness_report.json     full machine-readable evidence
  - executive_summary.md      one-page human summary
  - release-gate-evidence.html self-contained HTML dashboard

Usage:
    release-gate evidence-pack governance.yaml [options]
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional


def write_json_report(data: Dict[str, Any], path: str) -> str:
    Path(path).write_text(json.dumps(data, indent=2), encoding="utf-8")
    return path


def write_markdown_summary(data: Dict[str, Any], path: str) -> str:
    score    = data.get("readiness_score", 0)
    decision = data.get("decision", "UNKNOWN")
    project  = data.get("project", "AI Agent")
    ts       = data.get("generated_at", "")
    dims     = data.get("dimensions", {})
    crits    = data.get("critical_failures", [])
    evals    = data.get("eval_summary", {})
    traces   = data.get("trace_summary", {})
    impact   = data.get("impact_summary", {})

    decision_emoji = {"PROMOTE": "✅", "HOLD": "⚠️", "BLOCK": "\U0001f6ab"}.get(decision, "❓")

    lines = [
        f"# AI Release Readiness — {project}",
        f"",
        f"**Generated:** {ts}  ",
        f"**Decision:** {decision_emoji} **{decision}**  ",
        f"**Readiness Score:** {score}/100  ",
        f"",
        f"---",
        f"",
        f"## Dimension Scores",
        f"",
        f"| Dimension | Score |",
        f"|-----------|-------|"  ,
    ]
    for dim, info in dims.items():
        bar = "█" * (info["score"] // 10) + "░" * (10 - info["score"] // 10)
        lines.append(f"| {dim.replace('_', ' ').title()} | {info['score']}/100  {bar} |")

    lines += ["", "---", ""]

    if crits:
        lines += ["## ⛔ Critical Failures", ""]
        for f in crits:
            lines.append(f"- **[{f['source'].upper()}]** `{f['check']}` — {f['reason']}")
        lines.append("")

    if evals:
        lines += [
            "## Eval Results", "",
            f"- Total: {evals.get('total', 0)}",
            f"- Passed: {evals.get('passed', 0)}",
            f"- Failed: {evals.get('failed', 0)}",
            f"- Critical failures: {evals.get('critical_failed', 0)}",
            f"- Pass rate: {evals.get('pass_rate', 0):.1f}%",
            "",
        ]

    if traces:
        lines += [
            "## Trace Analysis", "",
            f"- Violations: {len(traces.get('violations', []))}",
            f"- Unauthorized tool calls: {traces.get('unauthorized_tool_calls', [])}",
            "",
        ]

    if impact:
        lines += [
            "## Cost Risk", "",
            f"- Normal daily cost: ${impact.get('normal_daily', 0):,.2f}",
            f"- Runaway scenario:  ${impact.get('runaway_daily', 0):,.2f}",
            f"- Risk delta:        ${impact.get('risk_delta_daily', 0):,.2f}/day",
            "",
        ]

    recommendation = {
        "PROMOTE": "All required checks passed — meets the configured release policy.",
        "HOLD":    "Governance passed but score below threshold — manual approval required.",
        "BLOCK":   "One or more critical failures. Do NOT ship until issues are resolved.",
    }.get(decision, "")

    lines += [
        "---", "",
        "## Recommendation", "",
        recommendation, "",
        "_Generated by release-gate — github.com/VamsiSudhakaran1/release-gate_",
    ]

    Path(path).write_text("\n".join(lines), encoding="utf-8")
    return path


_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>AI Release Readiness Evidence — {project}</title>
<style>
  *,*::before,*::after{{box-sizing:border-box;margin:0;padding:0;}}
  body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
       background:#0d1117;color:#c9d1d9;padding:2rem;line-height:1.6;}}
  h1{{color:#f0f6fc;font-size:1.5rem;border-bottom:1px solid #30363d;padding-bottom:.6rem;margin-bottom:1.2rem;}}
  h2{{color:#8b949e;font-size:.85rem;text-transform:uppercase;letter-spacing:.08em;margin:1.8rem 0 .6rem;}}
  .meta{{color:#8b949e;font-size:.8rem;margin-bottom:1.6rem;}}
  .decision-badge{{display:inline-block;padding:.4rem 1.2rem;border-radius:6px;
                   font-weight:700;font-size:1.1rem;margin-bottom:1.2rem;}}
  .badge-promote{{background:#1f4d2e;color:#3fb950;}}
  .badge-hold{{background:#4a3000;color:#d29922;}}
  .badge-block{{background:#4a1010;color:#f85149;}}
  .score-row{{display:flex;align-items:center;gap:16px;margin-bottom:1.4rem;}}
  .score-num{{font-size:3rem;font-weight:800;color:#f0f6fc;}}
  .score-label{{color:#8b949e;font-size:.9rem;}}
  .dim-grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px;margin-bottom:1.2rem;}}
  .dim-card{{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:14px;}}
  .dim-name{{font-size:.75rem;text-transform:uppercase;letter-spacing:.06em;color:#8b949e;margin-bottom:6px;}}
  .dim-score{{font-size:1.4rem;font-weight:700;color:#f0f6fc;}}
  .bar-wrap{{background:#21262d;border-radius:4px;height:6px;margin-top:8px;overflow:hidden;}}
  .bar-fill{{height:100%;border-radius:4px;}}
  .bar-green{{background:#3fb950;}}.bar-yellow{{background:#d29922;}}.bar-red{{background:#f85149;}}
  table{{width:100%;border-collapse:collapse;font-size:.875rem;margin-bottom:1rem;}}
  th{{text-align:left;color:#8b949e;font-weight:500;padding:.35rem .6rem;border-bottom:1px solid #21262d;}}
  td{{padding:.35rem .6rem;border-bottom:1px solid #161b22;}}
  .pass{{color:#3fb950;}}.warn{{color:#d29922;}}.fail{{color:#f85149;}}
  .crit{{background:rgba(248,81,73,.08);border-left:3px solid #f85149;padding:10px 14px;
         border-radius:0 6px 6px 0;margin-bottom:8px;font-size:.875rem;}}
  .crit-label{{font-size:.7rem;color:#8b949e;text-transform:uppercase;letter-spacing:.06em;}}
  .footer{{margin-top:2.4rem;color:#484f58;font-size:.75rem;border-top:1px solid #21262d;padding-top:1rem;}}
  .section{{background:#161b22;border:1px solid #30363d;border-radius:10px;padding:18px 22px;margin-bottom:1.2rem;}}
  code{{font-family:monospace;font-size:.85rem;background:#21262d;padding:2px 5px;border-radius:3px;}}
</style>
</head>
<body>
<h1>&#x1F6AA; release-gate &mdash; AI Release Readiness Evidence</h1>
<p class="meta"><strong>Project:</strong> {project} &nbsp;|&nbsp;
   <strong>Model:</strong> {model} &nbsp;|&nbsp;
   <strong>Generated:</strong> {timestamp}</p>

<span class="decision-badge badge-{decision_lower}">{decision}</span>

<div class="score-row">
  <div class="score-num">{score}</div>
  <div>
    <div class="score-label">Readiness Score / 100</div>
    <div class="score-label">Confidence: {confidence}</div>
  </div>
</div>

<h2>Dimension Breakdown</h2>
<div class="dim-grid">
{dim_cards}
</div>

{critical_section}
{eval_section}
{trace_section}
{impact_section}
{check_section}

<div class="footer">Generated by release-gate &mdash; github.com/VamsiSudhakaran1/release-gate</div>
</body>
</html>
"""


def _bar_color(score: int) -> str:
    if score >= 75: return "bar-green"
    if score >= 50: return "bar-yellow"
    return "bar-red"


def _dim_card(name: str, info: Dict) -> str:
    s = info.get("score", 0)
    return (
        f'<div class="dim-card">'
        f'<div class="dim-name">{name.replace("_", " ").title()}</div>'
        f'<div class="dim-score">{s}</div>'
        f'<div class="bar-wrap"><div class="bar-fill {_bar_color(s)}" style="width:{s}%"></div></div>'
        f'</div>'
    )


def render_html_evidence(data: Dict[str, Any], output_path: str) -> str:
    score    = data.get("readiness_score", 0)
    decision = data.get("decision", "UNKNOWN")
    project  = data.get("project", "AI Agent")
    model    = data.get("model", "unknown")
    ts       = data.get("generated_at", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"))
    dims     = data.get("dimensions", {})
    crits    = data.get("critical_failures", [])
    evals    = data.get("eval_summary", {})
    traces   = data.get("trace_summary", {})
    impact   = data.get("impact_summary", {})
    checks   = data.get("check_results", {})
    conf     = data.get("confidence", "low")

    dim_cards = "\n".join(_dim_card(n, i) for n, i in dims.items())

    if crits:
        crit_rows = "".join(
            f'<div class="crit"><span class="crit-label">[{f["source"]}] {f["check"]}</span><br>{f["reason"]}</div>'
            for f in crits
        )
        critical_section = (
            '<h2>&#x26D4; Critical Failures</h2>'
            f'<div class="section">{crit_rows}</div>'
        )
    else:
        critical_section = '<h2>Critical Failures</h2><div class="section"><p class="pass">&#x2713; No critical failures detected.</p></div>'

    if evals and evals.get("total", 0) > 0:
        rows = "".join(
            f'<tr><td>{r.get("name","")}</td>'
            f'<td><code>{r.get("category","")}</code></td>'
            f'<td><code>{r.get("severity","")}</code></td>'
            f'<td class="{"pass" if r.get("passed") else "fail"}">'  
            f'{"&#x2713; PASS" if r.get("passed") else "&#x2717; FAIL"}</td>'
            f'<td>{r.get("failure_reason") or "&mdash;"}</td></tr>'
            for r in evals.get("results", [])
        )
        eval_section = (
            f'<h2>Eval Results &nbsp; <small>{evals["passed"]}/{evals["total"]} passed '
            f'({evals.get("pass_rate",0):.0f}%)</small></h2>'
            '<div class="section"><table>'
            '<tr><th>Test</th><th>Category</th><th>Severity</th><th>Result</th><th>Reason</th></tr>'
            f'{rows}</table></div>'
        )
    else:
        eval_section = '<h2>Eval Results</h2><div class="section"><p class="warn">No evals configured. Add an evals.yaml for LLM behavior testing.</p></div>'

    if traces:
        viols = traces.get("violations", [])
        warns = traces.get("warnings", [])
        css   = "fail" if viols else ("warn" if warns else "pass")
        viol_html = "".join(f"<li class='fail'>{v}</li>" for v in viols)
        warn_html = "".join(f"<li class='warn'>{w}</li>" for w in warns)
        trace_section = (
            f'<h2>Trace Analysis &nbsp; <small class="{css}">{traces.get("status","")}</small></h2>'
            f'<div class="section"><ul>{viol_html}{warn_html}</ul>'
            f'<p style="margin-top:8px;color:#8b949e">Traces: {traces.get("trace_count",0)}</p></div>'
        )
    else:
        trace_section = '<h2>Trace Analysis</h2><div class="section"><p class="warn">No trace file provided. Pass --traces to evaluate agent behavior.</p></div>'

    if impact:
        impact_section = (
            '<h2>Cost Risk</h2><div class="section"><table>'
            '<tr><th>Scenario</th><th>Daily</th><th>Monthly</th></tr>'
            f'<tr><td>Normal</td><td>${impact.get("normal_daily",0):,.2f}</td><td>${impact.get("normal_daily",0)*30:,.2f}</td></tr>'
            f'<tr style="color:#f85149"><td>Runaway</td><td>${impact.get("runaway_daily",0):,.2f}</td><td>${impact.get("runaway_daily",0)*30:,.2f}</td></tr>'
            f'<tr style="color:#d29922;font-weight:600"><td>Risk delta</td><td>${impact.get("risk_delta_daily",0):,.2f}</td><td>${impact.get("risk_delta_daily",0)*30:,.2f}</td></tr>'
            '</table></div>'
        )
    else:
        impact_section = ""

    if checks:
        rows = "".join(
            f'<tr><td>{name}</td>'
            f'<td class="{"pass" if r.get("status")=="PASS" else ("warn" if r.get("status")=="WARN" else "fail")}">'
            f'{r.get("status","UNKNOWN")}</td></tr>'
            for name, r in sorted(checks.items())
        )
        check_section = (
            '<h2>Governance Checks</h2><div class="section"><table>'
            '<tr><th>Check</th><th>Status</th></tr>'
            f'{rows}</table></div>'
        )
    else:
        check_section = ""

    html = _HTML_TEMPLATE.format(
        project=project, model=model, timestamp=ts,
        decision=decision, decision_lower=decision.lower(),
        score=score, confidence=conf,
        dim_cards=dim_cards,
        critical_section=critical_section,
        eval_section=eval_section,
        trace_section=trace_section,
        impact_section=impact_section,
        check_section=check_section,
    )

    Path(output_path).write_text(html, encoding="utf-8")
    return output_path


def generate_evidence_pack(data: Dict[str, Any], output_dir: str = "release-evidence") -> Dict[str, str]:
    """Write all three evidence artefacts and return their paths."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    json_path = str(out / "readiness_report.json")
    md_path   = str(out / "executive_summary.md")
    html_path = str(out / "release-gate-evidence.html")

    write_json_report(data, json_path)
    write_markdown_summary(data, md_path)
    render_html_evidence(data, html_path)

    return {"json": json_path, "markdown": md_path, "html": html_path}
