"""release-gate assurance layer.

The evidence and authorisation model described in
`docs/specs/universal-assurance-architecture.md`. Built incrementally; this
package currently provides the central case object, the exact subject a human is
asked to authorise, the record collections a case is built from, the
methodology a case is argued against, and the canonical digest machinery they
all rest on.

Nothing here imports an LLM client, makes a network call, or executes ingested
content. The authoritative assurance path is deterministic, and these are its
foundations.
"""

from __future__ import annotations

from release_gate.assurance.canonical import (
    CanonicalisationError,
    canonical_json,
    digest_bytes,
    digest_file,
    digest_items,
    digest_object,
    is_content_id,
    is_digest,
    is_git_object_id,
    merkle_root,
)
from release_gate.assurance.case import (
    CASE_BINDING_ALGO,
    COLLECTION_KINDS,
    EVIDENCE_KINDS,
    AssuranceCase,
    AssuranceCaseBuilder,
    CaseIntegrityError,
    CaseState,
    CaseStateError,
    CaseType,
    CaseValidationError,
    CaseVerdict,
    Decision,
    MethodologyRef,
    default_case_type,
)
from release_gate.assurance.evidence import (
    EVIDENCE_SCHEMA_VERSION,
    CoverageStatus,
    EpistemicStatus,
    EvidenceError,
    EvidenceIntegrityError,
    EvidenceRecord,
    EvidenceSchemaError,
    EvidenceType,
    Producer,
    ProducerKind,
    ProvenanceStatus,
    TrustDecision,
    TrustStatus,
    VerificationMethod,
    external_content,
    file_content,
    inline_content,
)
from release_gate.assurance.methodologies import (
    BUILTIN_METHODOLOGIES,
    default_registry,
)
from release_gate.assurance.methodology import (
    ALL_CASE_TYPES,
    AssessmentStatus,
    AssuranceMethodology,
    CoverageExpectation,
    Criticality,
    CriticalityRule,
    EvidenceExpectation,
    IndependenceRequirement,
    MethodologyAssessment,
    MethodologyDriftError,
    MethodologyError,
    MethodologyRegistry,
    OverrideRule,
    Requirement,
    RequirementEffect,
    RequirementOutcome,
    RequirementResult,
    assess,
    assess_case,
    predicate_from_dict,
)
from release_gate.assurance.records import (
    CaseRecord,
    DedupeBasis,
    MaterialisationBasis,
    Presence,
    RecordCollection,
    RecordCollectionBuilder,
    RecordError,
    SimpleRecord,
    record_digest,
)
from release_gate.assurance.subject import (
    AssuranceSubject,
    ContentReference,
    DigestMethod,
    DigestStatus,
    MutationCheck,
    MutationStatus,
    ReferenceKind,
    SubjectIntegrityError,
    SubjectType,
    SubjectValidationError,
    VersionBasis,
    describe_supersession,
    directory_manifest_digest,
)

__all__ = [
    "ALL_CASE_TYPES",
    "AssessmentStatus",
    "AssuranceCase",
    "AssuranceCaseBuilder",
    "AssuranceMethodology",
    "AssuranceSubject",
    "BUILTIN_METHODOLOGIES",
    "CASE_BINDING_ALGO",
    "COLLECTION_KINDS",
    "CanonicalisationError",
    "CaseIntegrityError",
    "CaseRecord",
    "CaseState",
    "CaseStateError",
    "CaseType",
    "CaseValidationError",
    "CaseVerdict",
    "ContentReference",
    "CoverageExpectation",
    "CoverageStatus",
    "Criticality",
    "CriticalityRule",
    "Decision",
    "DedupeBasis",
    "DigestMethod",
    "DigestStatus",
    "EVIDENCE_KINDS",
    "EVIDENCE_SCHEMA_VERSION",
    "EpistemicStatus",
    "EvidenceError",
    "EvidenceExpectation",
    "EvidenceIntegrityError",
    "EvidenceRecord",
    "EvidenceSchemaError",
    "EvidenceType",
    "IndependenceRequirement",
    "MaterialisationBasis",
    "MethodologyAssessment",
    "MethodologyDriftError",
    "MethodologyError",
    "MethodologyRef",
    "MethodologyRegistry",
    "MutationCheck",
    "MutationStatus",
    "OverrideRule",
    "Presence",
    "Producer",
    "ProducerKind",
    "ProvenanceStatus",
    "RecordCollection",
    "RecordCollectionBuilder",
    "RecordError",
    "ReferenceKind",
    "Requirement",
    "RequirementEffect",
    "RequirementOutcome",
    "RequirementResult",
    "SimpleRecord",
    "SubjectIntegrityError",
    "SubjectType",
    "SubjectValidationError",
    "TrustDecision",
    "TrustStatus",
    "VerificationMethod",
    "VersionBasis",
    "assess",
    "assess_case",
    "canonical_json",
    "default_case_type",
    "default_registry",
    "describe_supersession",
    "digest_bytes",
    "digest_file",
    "digest_items",
    "digest_object",
    "directory_manifest_digest",
    "external_content",
    "file_content",
    "inline_content",
    "is_content_id",
    "is_digest",
    "is_git_object_id",
    "merkle_root",
    "predicate_from_dict",
    "record_digest",
]
