"""The Admission Report — what is being admitted, under which policy, and why the answer is what it is.

A scanner report answers "what did the scanner find". This answers a different
question: *may this exact release be admitted, and on what basis?* It is read
from an assurance outcome — the sealed case, the admission evaluation, the
claim resolution and the evidence origin — and computes nothing of its own: no
decision, no status, no count that another part of the engine did not already
produce. The scanner's report, its SARIF and every other output stay as they
are; this sits above them.

In the order a person reads it:

1. **Candidate, state hash, policy, decision.** The release being admitted
   (its components and who stated them), the digest that identifies it, the
   methodology and resolution policy the decision was taken under (by
   reference and digest), and PROMOTE / HOLD / BLOCK with the sentence that
   says why.
2. **Critical claims**, by where their resolution left them: established,
   supported, partially supported, contradicted, unsupported, unknown, not
   assessed. Critical means the decision rests on it; a claim whose criticality
   could not be determined is listed here too, and said so.
3. **What stands in the way**: blocking reasons, what needs a person,
   contradictions, counterexamples, coverage gaps, evidence bound to another
   state, and independence concerns.
4. **Evidence sources**, split by what release-gate did with them:
   *generated by Release-Gate* (computed in this run, or a document a
   release-gate run produced and this run read), *obtained in this run* (a
   model asked at release-gate's request), and *imported evidence* (another
   system's account, read and never re-run).
5. **Summaries**, marked as such: the assurance level reached and required.
   A summary is never an input to the decision, and the report says so.

`AdmissionReport.to_dict()` is the same report as data.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Mapping, Sequence, Tuple

__all__ = [
    "ADMISSION_REPORT_SCHEMA_VERSION",
    "AdmissionReport",
    "EvidenceSource",
    "build_admission_report",
    "render_admission_report",
]

ADMISSION_REPORT_SCHEMA_VERSION = 1

#: Claim statuses in the order the report lists them. The first is what a
#: release wants; the rest are what stands between it and that.
_STATUS_ORDER = ("ESTABLISHED", "SUPPORTED", "PARTIALLY_SUPPORTED", "CONTRADICTED",
                 "UNSUPPORTED", "UNKNOWN", "NOT_ASSESSED")
#: Always listed, even empty: "none contradicted" is something a reader looks for.
_ALWAYS_SHOWN = ("ESTABLISHED", "PARTIALLY_SUPPORTED", "CONTRADICTED", "UNKNOWN",
                 "NOT_ASSESSED")
_STATUS_LABEL = {"ESTABLISHED": "Established", "SUPPORTED": "Supported",
                 "PARTIALLY_SUPPORTED": "Partially supported",
                 "CONTRADICTED": "Contradicted", "UNSUPPORTED": "Unsupported",
                 "UNKNOWN": "Unknown", "NOT_ASSESSED": "Not assessed"}

#: What a producer is, by the contract it arrived through.
_PRODUCER_TYPE_LABEL = {
    "release_gate_static": "Release-Gate Static", "promptfoo": "Promptfoo",
    "sarif": "SARIF", "eval": "Eval harness", "red_team": "Red team",
    "sast": "SAST", "human_review": "Human review",
    "behavior": "Behavioural evaluation",
    "external_decision": "External decision",
}
#: Traces, by the format they were read from.
_TRACE_LABEL = {"LANGFUSE_EXPORT": "Langfuse", "OTLP_TRACE": "OpenTelemetry",
                "ARIZE_EXPORT": "Arize / Phoenix",
                "ORCHESTRATOR_EXPORT": "Orchestrator trace", "NATIVE_TRACE": "Trace"}


@dataclass(frozen=True)
class EvidenceSource:
    """One producer whose evidence the case holds, and how it came to hold it."""

    label: str
    producer: str
    records: int
    evidence_types: Mapping[str, int] = field(default_factory=dict)
    statement: str = ""
    sources: Tuple[str, ...] = ()

    def to_dict(self) -> Dict[str, Any]:
        return {"label": self.label, "producer": self.producer, "records": self.records,
                "evidence_types": dict(self.evidence_types),
                "statement": self.statement, "sources": list(self.sources)}


@dataclass(frozen=True)
class AdmissionReport:
    """The admission artifact. Every field is read from an outcome; none is computed here."""

    decision: str
    basis: str
    exit_code: int
    case_id: str = ""
    case_digest: str = ""
    candidate: Mapping[str, str] = field(default_factory=dict)
    candidate_source: str = ""
    state_hash: str = ""
    state_hash_basis: str = ""
    policy: Mapping[str, Any] = field(default_factory=dict)
    criticality_determinable: bool = False
    critical_claims: Mapping[str, Tuple[Mapping[str, Any], ...]] = field(default_factory=dict)
    other_claims: int = 0
    blocking: Tuple[Mapping[str, Any], ...] = ()
    attention: Tuple[Mapping[str, Any], ...] = ()
    contradictions: Tuple[Mapping[str, Any], ...] = ()
    counterexamples: Tuple[Mapping[str, Any], ...] = ()
    coverage_gaps: Tuple[Mapping[str, Any], ...] = ()
    state_binding_failures: Tuple[Mapping[str, Any], ...] = ()
    independence_concerns: Tuple[Mapping[str, Any], ...] = ()
    dimensions: Tuple[Mapping[str, Any], ...] = ()
    generated: Tuple[EvidenceSource, ...] = ()
    obtained: Tuple[EvidenceSource, ...] = ()
    imported: Tuple[EvidenceSource, ...] = ()
    summaries: Mapping[str, Any] = field(default_factory=dict)

    @property
    def decided_by_score(self) -> bool:
        """Unconditionally false: no score, level or count is an input to admission."""
        return False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "record_type": "admission_report",
            "schema_version": ADMISSION_REPORT_SCHEMA_VERSION,
            "decision": self.decision, "basis": self.basis, "exit_code": self.exit_code,
            "case_id": self.case_id, "case_digest": self.case_digest,
            "candidate": {"components": dict(self.candidate),
                          "source": self.candidate_source,
                          "state_hash": self.state_hash,
                          "state_hash_basis": self.state_hash_basis},
            "policy": dict(self.policy),
            "critical_claims": {
                "criticality_determinable": self.criticality_determinable,
                "by_status": {status: [dict(c) for c in claims]
                              for status, claims in self.critical_claims.items()},
                "other_claims": self.other_claims},
            "blocking_reasons": [dict(c) for c in self.blocking],
            "human_attention": [dict(a) for a in self.attention],
            "contradictions": [dict(c) for c in self.contradictions],
            "counterexamples": [dict(c) for c in self.counterexamples],
            "coverage_gaps": [dict(c) for c in self.coverage_gaps],
            "state_binding_failures": [dict(b) for b in self.state_binding_failures],
            "independence_concerns": [dict(c) for c in self.independence_concerns],
            "dimensions": [dict(d) for d in self.dimensions],
            "evidence_sources": {
                "generated_by_release_gate": [s.to_dict() for s in self.generated],
                "obtained_in_this_run": [s.to_dict() for s in self.obtained],
                "imported": [s.to_dict() for s in self.imported]},
            "summaries": dict(self.summaries),
            "decided_by_score": self.decided_by_score,
        }


# ── building it ──────────────────────────────────────────────────────────────

def _label(entry: Any, detection_kind: str) -> str:
    producer = entry.producer_id
    if producer.startswith("release-gate/static"):
        return "Release-Gate Static"
    if producer.startswith("release-gate/"):
        return "Release-Gate"
    for producer_type in entry.producer_types:
        if producer_type in _PRODUCER_TYPE_LABEL:
            return _PRODUCER_TYPE_LABEL[producer_type]
    types = set(entry.evidence_types)
    if "FORMAL_PROOF" in types:
        return "Formal verification"
    if types and types <= {"HUMAN_REVIEW", "APPROVAL"}:
        return "Human review"
    if "CLAIM_DERIVATION" in types and producer.startswith("model://"):
        return "Semantic verifier (a model's reading)"
    if "TRACE" in types:
        return _TRACE_LABEL.get(detection_kind, "Runtime trace")
    return "External evidence"


def _sources(outcome: Any) -> Tuple[List[EvidenceSource], List[EvidenceSource],
                                    List[EvidenceSource]]:
    from release_gate.assurance.origin import OriginKind
    detection = getattr(getattr(outcome, "detection", None), "kind", None)
    kind = getattr(detection, "value", "") or ""
    generated: List[EvidenceSource] = []
    obtained: List[EvidenceSource] = []
    imported: List[EvidenceSource] = []
    for entry in outcome.evidence_origin.entries:
        source = EvidenceSource(
            label=_label(entry, kind), producer=entry.who, records=entry.records,
            evidence_types=dict(entry.evidence_types), statement=entry.statement,
            sources=tuple(entry.sources))
        if entry.origin is OriginKind.COMPUTED_HERE or entry.producer_id.startswith(
                "release-gate/"):
            # Release-gate's own work: this run's, or a release-gate run's
            # document read now, which the statement says is attributed.
            generated.append(source)
        elif entry.origin is OriginKind.OBTAINED_HERE:
            obtained.append(source)
        else:
            imported.append(source)
    return generated, obtained, imported


def _candidate(outcome: Any) -> Tuple[Dict[str, str], str, str, str]:
    binding = getattr(outcome.analysis, "state_binding", None)
    candidate = getattr(binding, "candidate", None)
    if candidate is None:
        from release_gate.assurance.candidate import candidate_for_case
        candidate, _notes = candidate_for_case(outcome.case)
    if candidate is None:
        return ({}, "", outcome.case.case_digest,
                "no candidate state was stated or derivable; this is the case digest, "
                "which binds the evidence held and not a release")
    source = candidate.source.value + (f" ({candidate.declared_by})"
                                       if candidate.declared_by else "")
    return (dict(candidate.components), source, candidate.digest(),
            "digest of the candidate's components (candidate.py)")


def _claims(evaluation: Any) -> Tuple[bool, Dict[str, Tuple[Dict[str, Any], ...]], int]:
    grouped: Dict[str, List[Dict[str, Any]]] = {s: [] for s in _STATUS_ORDER}
    determinable = any(c.required is not None for c in evaluation.claims)
    other = 0
    for claim in evaluation.claims:
        if claim.required is False:
            other += 1
            continue
        grouped.setdefault(claim.status, []).append(
            {"claim_id": claim.claim_id, "statement": claim.statement,
             "rule": claim.rule, "basis": claim.basis,
             "criticality": ("required" if claim.required else "undetermined"),
             "conditions": list(claim.conditions)})
    shown = {s: tuple(grouped.get(s, ())) for s in _STATUS_ORDER
             if s in _ALWAYS_SHOWN or grouped.get(s)}
    return determinable, shown, other


def _condition(c: Any) -> Dict[str, Any]:
    return {"condition_id": c.condition_id, "dimension": c.dimension.value,
            "effect": c.effect.value, "summary": c.summary, "claims": list(c.claims),
            "declared_by": c.declared_by, "remedy": c.remedy}


def build_admission_report(outcome: Any, *, attention_limit: int = 12) -> AdmissionReport:
    """Read one assurance outcome into the admission artifact. Computes no decision."""
    from release_gate.assurance.admission import AdmissionDimension, ConditionEffect
    from release_gate.assurance.authorship import AuthorIndependence
    from release_gate.assurance.counterexample import CounterexampleStanding

    evaluation = outcome.admission
    if evaluation is None:
        raise ValueError("an outcome with no admission evaluation cannot be reported "
                         "as an admission")
    analysis = outcome.analysis
    components, source, state_hash, state_basis = _candidate(outcome)
    determinable, critical, other = _claims(evaluation)

    attention = tuple(
        {"effect": item.effect.value, "focus_kind": item.focus_kind, "focus": item.focus,
         "summary": item.summary, "remedy": item.remedy, "rules": list(item.rule_ids)}
        for item in list(outcome.attention.items)[:attention_limit])

    contradictions = tuple(
        {"contradiction_id": c.contradiction_id, "claims": list(c.target_claims),
         "class": c.classification.value, "is_contradiction": c.is_contradiction,
         "critical": c.affects_critical, "status": c.status.value,
         "described": c.described,
         "sides": [f"{side.label} {len(side.evidence)} record(s)" for side in c.sides]}
        for c in outcome.contradictions.open())

    standing = {s.counterexample_id: s for s in analysis.counterexample_standings}
    counterexamples = tuple(
        {"counterexample_id": a.counterexample_id, "claim": a.target_claim,
         "producer": a.producer, "result": a.result.value, "status": a.status.value,
         "standing": (standing[a.counterexample_id].standing.value
                      if a.counterexample_id in standing else ""),
         "reason": (standing[a.counterexample_id].reason
                    if a.counterexample_id in standing else "")}
        for a in outcome.counterexamples.attempts
        if a.counterexample_id not in standing
        or standing[a.counterexample_id].standing is not CounterexampleStanding.NOT_FOUND)

    gaps: List[Dict[str, Any]] = []
    coverage = analysis.claim_coverage
    for claim in (coverage.stated if coverage is not None else ()):
        missing = [f"{e.dimension} {e.element}" for e in claim.missing]
        if missing:
            gaps.append({"claim": claim.claim_id, "missing": missing,
                         "required": claim.required})
    for condition in evaluation.in_dimension(AdmissionDimension.COVERAGE):
        if condition.effect in (ConditionEffect.BLOCK, ConditionEffect.HOLD):
            gaps.append({"condition": condition.condition_id, "summary": condition.summary,
                         "claims": list(condition.claims)})

    failures: List[Dict[str, Any]] = []
    binding = analysis.state_binding
    if binding is not None:
        explicit = binding.candidate.explicit
        for b in binding.bindings:
            if b.match.value in ("STALE", "INCOMPATIBLE") or (
                    explicit and b.match.value == "UNKNOWN" and b.supports):
                failures.append({"record": b.record_id, "kind": b.record_kind,
                                 "binding": b.match.value, "claims": list(b.bears_on),
                                 "reason": b.reason})

    concerns: List[Dict[str, Any]] = [
        _condition(c) for c in evaluation.in_dimension(AdmissionDimension.INDEPENDENCE)
        if c.effect in (ConditionEffect.BLOCK, ConditionEffect.HOLD,
                        ConditionEffect.ADVISORY)]
    authorship = analysis.authorship
    if authorship is not None and authorship.present:
        for row in authorship.claims:
            if row.status in (AuthorIndependence.LOW, AuthorIndependence.UNDETERMINED):
                concerns.append({"claim": row.claim_id, "authorship": row.status.value,
                                 "summary": row.basis})

    generated, obtained, imported = _sources(outcome)
    level = getattr(outcome, "level", None)
    summaries = {
        "note": ("summaries only: none of these is an input to the decision, and no "
                 "score can override a blocking condition"),
        "assurance_level_supported": getattr(getattr(level, "supported", None), "name",
                                             None),
        "assurance_level_required": getattr(getattr(level, "required", None), "name",
                                            None),
        "conditions": {e.value: len(evaluation.of(e)) for e in ConditionEffect},
    }
    return AdmissionReport(
        decision=evaluation.decision.value, basis=evaluation.basis,
        exit_code=outcome.exit_code, case_id=outcome.case.case_id,
        case_digest=outcome.case.case_digest, candidate=components,
        candidate_source=source, state_hash=state_hash, state_hash_basis=state_basis,
        policy=dict(evaluation.policy), criticality_determinable=determinable,
        critical_claims=critical, other_claims=other,
        blocking=tuple(_condition(c) for c in evaluation.blocking),
        attention=attention, contradictions=contradictions,
        counterexamples=counterexamples, coverage_gaps=tuple(gaps),
        state_binding_failures=tuple(failures),
        independence_concerns=tuple(concerns),
        dimensions=tuple(d.to_dict() for d in evaluation.dimensions()),
        generated=tuple(generated), obtained=tuple(obtained), imported=tuple(imported),
        summaries=summaries)


# ── rendering ────────────────────────────────────────────────────────────────

def _section(lines: List[str], title: str, rows: Sequence[str]) -> None:
    lines.append("")
    lines.append(f"  {title} ({len(rows)})" if rows else f"  {title} — none")
    for row in rows:
        lines.append(f"    {row}")


def _sources_block(lines: List[str], title: str, rows: Sequence[EvidenceSource],
                   empty: str) -> None:
    lines.append(f"    {title}")
    if not rows:
        lines.append(f"      {empty}")
    for row in rows:
        kinds = ", ".join(f"{n} {t}" for t, n in sorted(row.evidence_types.items()))
        lines.append(f"      {row.label} — {row.producer}: {row.records} record(s) ({kinds})")
        lines.append(f"        {row.statement}")


def render_admission_report(report: AdmissionReport) -> str:
    """The admission report as text. Reads the report's fields and nothing else."""
    lines: List[str] = ["", "=" * 78, "  ADMISSION REPORT", "=" * 78, ""]
    candidate = (" · ".join(f"{k} {v}" for k, v in sorted(report.candidate.items()))
                 or "none stated")
    policy = report.policy
    methodology = policy.get("methodology") or "none (METHODOLOGY_REQUIRED)"
    if policy.get("methodology_digest"):
        methodology += f" ({str(policy['methodology_digest'])[:19]}…)"
    resolution = policy.get("resolution_policy") or "default"
    if policy.get("resolution_policy_digest"):
        resolution += f" ({str(policy['resolution_policy_digest'])[:19]}…)"
    lines += [f"  Candidate    {candidate}",
              *([f"               stated by {report.candidate_source}"]
                if report.candidate_source else []),
              f"  State hash   {report.state_hash}",
              f"  Policy       methodology {methodology}",
              f"               resolution {resolution} · ruleset {policy.get('ruleset')}",
              f"  Decision     {report.decision}",
              f"               {report.basis}"]

    total = sum(len(v) for v in report.critical_claims.values())
    lines.append("")
    lines.append(f"  CRITICAL CLAIMS ({total})" + (
        "" if report.criticality_determinable
        else " — criticality could not be determined, so every claim is listed"))
    for status, claims in report.critical_claims.items():
        lines.append(f"    {_STATUS_LABEL[status]} ({len(claims)})")
        for claim in claims:
            lines.append(f"      {claim['claim_id']}  {claim['statement']}  [{claim['rule']}]")
    if report.other_claims:
        lines.append(f"    + {report.other_claims} claim(s) the decision does not rest on")

    _section(lines, "BLOCKING REASONS", [
        f"{c['condition_id']}  [{c['dimension']}]  {c['summary']}"
        + (f"  — on {', '.join(c['claims'])}" if c["claims"] else "")
        for c in report.blocking])
    _section(lines, "HUMAN ATTENTION REQUIRED", [
        f"[{a['effect']:>8}]  {a['focus_kind']}: {a['focus']} — {a['summary']}"
        + (f"  -> {a['remedy']}" if a["remedy"] else "") for a in report.attention])
    _section(lines, "CONTRADICTIONS", [
        f"{c['contradiction_id']}  {', '.join(c['claims'])}  {c['class']}"
        + ("  CRITICAL" if c["critical"] else "") + f" — {' vs '.join(c['sides'])}"
        for c in report.contradictions])
    _section(lines, "COUNTEREXAMPLES", [
        f"{c['counterexample_id']}  {c['claim']}  {c['standing'] or c['status']} "
        f"(by {c['producer']})" + (f" — {c['reason']}" if c["reason"] else "")
        for c in report.counterexamples])
    _section(lines, "COVERAGE GAPS", [
        (f"{g['claim']}: missing {', '.join(g['missing'][:6])}" if "missing" in g
         else f"{g['condition']}: {g['summary']}") for g in report.coverage_gaps])
    _section(lines, "STATE-BINDING FAILURES", [
        f"{b['record']} ({b['kind']}, {b['binding']}) on {', '.join(b['claims'])} — "
        f"{b['reason']}" for b in report.state_binding_failures])
    _section(lines, "INDEPENDENCE CONCERNS", [
        (f"{c['condition_id']}  [{c['effect']}]  {c['summary']}" if "condition_id" in c
         else f"{c['claim']}  [{c['authorship']}]  {c['summary']}")
        for c in report.independence_concerns])

    lines.append("")
    lines.append("  EVIDENCE SOURCES")
    _sources_block(lines, "Generated by Release-Gate", report.generated,
                   "none")
    if report.obtained:
        _sources_block(lines, "Obtained by Release-Gate in this run (another system's "
                              "reading)", report.obtained, "none")
    _sources_block(lines, "Imported evidence — read; Release-Gate did not run it",
                   report.imported, "none: every record here is release-gate's own")

    summaries = report.summaries
    lines.append("")
    lines.append("  SUMMARIES — not inputs to the decision")
    lines.append(f"    Assurance level  {summaries.get('assurance_level_supported')} "
                 f"supported · {summaries.get('assurance_level_required')} required")
    lines.append("    Conditions       " + ", ".join(
        f"{n} {e.lower()}" for e, n in summaries.get("conditions", {}).items() if n))
    lines.append(f"    {summaries.get('note')}")
    lines.append("")
    lines.append(f"  Decision: {report.decision} (exit {report.exit_code})")
    lines.append("=" * 78)
    return "\n".join(lines)
